#ifndef __COMMON_H
#define __COMMON_H
#include <fcntl.h>
#include <sys/file.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#include <stdio.h>
#define DISK_STORE 1024*4 //in bytes
#define FSS_FILENAME "fss.dat"
#define BLOCK_SIZE 128
//#define MAX_BRANCHES_TO_NODE 30 Not reqd
#define TOTAL_BLOCKS DISK_STORE/BLOCK_SIZE
#define INODE_COUNT (TOTAL_BLOCKS/4)  /*INODE_COUNT total number of inodes*/
//#define INODE_COUNT
#define DATABLOCK_COUNT TOTAL_BLOCKS-(INODE_COUNT+1) //1 IS FOR SUPER BLOCK

#define SIZE_OF_FILE_STRUCT sizeof(struct file)
#define SIZE_OF_DATABLOCK BLOCK_SIZE    //this define constant is junk
#define START_ADDR_SUPER_BLOCK 0
#define START_ADDR_HIERARCHY_LIST START_ADDR_SUPER_BLOCK+SIZE_OF_SUPER_BLOCK
#define START_ADDR_BMP_LIST
#define START_ADDR_DATA_BLOCK
#define FILE_SYSTEM_NULL -1
#define FILE_HANDLE unsigned int
#define NULL_CHAR '\0'
#define ZERO_CHAR '0'
#define BLANK_CHAR ''
#define BITMAP unsigned char
#define BYTE unsigned char
#define DATA_BLOCK int

#define MAX_LENGTH 256
#define MAX_LEN_COMMANDS 10
#define MAX_ARGS 3
#define END_OF_STRING -1
#define NO_OF_COMMANDS 12
#define FILE_ERROR -1
#define MAX_FILE_NAME_LEN 5


#define FSS_NO_ERROR 17
#define FSS_COMMANND_NOT_FOUND FSS_NO_ERROR+1
#define FSS_COMMAND_READ_ERROR FSS_NO_ERROR+2
#define FSS_BAD_COMMAND FSS_NO_ERROR+3
#define FSS_DISK_OPEN_ERROR FSS_NO_ERROR+4
#define FSS_DISK_READ_ERROR FSS_NO_ERROR+5
#define FSS_DISK_SEEK_ERROR FSS_NO_ERROR+6
#define FSS_DISK_WRITE_ERROR FSS_NO_ERROR+5


#define FILE_SYSTEM_NO_ERROR -1
#define FILE_CREATE_ERROR FILE_SYSTEM_NO_ERROR-1
#define FILE_NUMERICAL_LMT_EXCEEDS FILE_SYSTEM_NO_ERROR-2
#define FILE_WRITE_ERROR FILE_SYSTEM_NO_ERROR-3
#define FILE_SYS_NO_FREE_SPACE FILE_SYSTEM_NO_ERROR-4
#define FILE_NAME_CHAR_EXCEEDS FILE_SYSTEM_NO_ERROR-5
#define FILE_OPEN_ERROR FILE_SYSTEM_NO_ERROR-6
#define FILE_SYS_INVALID_USER FILE_SYSTEM_NO_ERROR-7
#define FILE_SYS_FILE_NUMERICAL_LMT_IN_DIRACTORY_EXCEEDS FILE_SYSTEM_NO_ERROR-8
#define FILE_COPY_ERROR FILE_SYSTEM_NO_ERROR-9
#define FILE_PASTE_ERROR FILE_SYSTEM_NO_ERROR-10
#define FILE_NAME_DUPLICATE_ERROR FILE_SYSTEM_NO_ERROR-11
#define FILE_SYS_FILE_NOT_FOUND_ERROR FILE_SYSTEM_NO_ERROR-12
#define FILE_DELETION_ERROR FILE_SYSTEM_NO_ERROR-13
#define FILE_NAME_CHAR_ILLEGAL FILE_SYSTEM_NO_ERROR-14
#define FILE_NAME_CHAR_INVALID FILE_SYSTEM_NO_ERROR-15

#define FILE_SYSTEM_MOUNT_FAILED -200


#define DENTRIES_PER_BLOCK SIZE_OF_DATABLOCK/SIZE_OF_STRUCT_DENTRY
#define DIR_NAME_SPACE_PER_CHAR
#define INVALID_FILE_NAME_LENGTH
#define INVALID_FILE_NAME
#define NOT_FOUND -1
enum OPERATION{
READ_FSS,
WRITE_FSS
};
enum COMMANDS{
	MKDIR = 1,
	RMDIR,
	CDDIR,
	OPEN,
	WRITE,
	DEL,
	FSINFO,
	LIST,
	LINK,
	UNLINK,
	FIND,
	CHMOD,
	CREAT,
	READ,
	CDBACK,
	RM,
	PWD
};

#endif
